### ISSUE TITLE
Utilize meteor-application-template

### ISSUE THREAD

**Issue by gbfrancisco** [manoafixit/manoafixit#1]
Do all work for this task in a branch called 'issue-1'.

* Use the meteor-application-template to set up a temporary "framework" for our website.
* Rename folders and files to their respective functions, i.e. rename *StuffItem* to something like *Problems* or *Suggestions*.
* Edit *settings.development.json* so that there is only one to three admin account(s).

**Comment by gcalica** [comment]
Dev branch has been created with meteor-application-template installed. API will be handled in a separate issue.
