### ISSUE TITLE
Create a Modal for the Submit page (Mobile)

### ISSUE THREAD

**Issue by gcalica** [manoafixit/manoafixit#45]
See #33 
Do this work in the branch feature/submit

- [x] Create a Modal for the submit page when the user denies location permission
- [x] Give instructions on how to reset location permission for each browser

All relevant files for this issue are found in ui/components/submit in the 'feature/submit' branch.

**Comment by gcalica** [comment]
For each browser, add a picture where resetting "Location Permissions" is. For Chrome, its on the far right of the URL bar. For Mozilla, its on the far left of the URL bar.

**Comment by gbfrancisco** [comment]
Instructions Completed
